### ISSUE TITLE
[BUG] Dice so Nice: Warnings in console

### ISSUE THREAD

**Issue by ianm32** [arcanistzed/custom-fonts#8] opened 2022-01-14 03:10 UTC
When loading Foundry and watching the console, I notice a number of warnings and some errors that seem to involve the Custom Fonts module.  It looks like it also involves the Dice So Nice module, so perhaps the two are clashing in some way.  I don't notice any impact on the user experience within Foundry, but I thought it might be worth sharing.
![6](https://user-images.githubusercontent.com/27756065/149444968-4645b03e-a974-42cc-9048-65ad34702c66.JPG)
![7](https://user-images.githubusercontent.com/27756065/149445006-79fb511e-5a37-412e-bbce-aa391e18f60e.JPG)

**Comment by arcanistzed** [comment] 2022-01-14 03:17
This looks like more of a Dice so Nice bug. I'm using it's public API.

**Comment by arcanistzed** [comment] 2022-01-14 03:18
The warnings specifically are likely because of a non-standard formatting in your font files, but I wouldn't worry about them.
I'm more concerned about the two error messages...

**Comment by ianm32** [comment] 2022-01-14 03:34
Gotcha.  In that case, I'm guessing that the warnings are coming from fonts included with the Custom Journal module, as I'm otherwise only using Google fonts, not any local font files.

**Comment by arcanistzed** [comment] 2022-01-14 03:54
Ok, I'll take a look at those font files. I just had a chat with JDW (dev of DSN) and I'll be working on a fix for the issue. It seems it's because the fonts are taking too long to load as DSN times out after 3 seconds.

**Comment by scooper4711** [comment] 2022-01-30 23:12
Just letting you know that I have the same issue. Watching this space for a fix.
Thanks for picking up this plugin!

**Comment by ravingdragoon** [comment] 2022-02-16 20:00
I have this issue as well

**Comment by arcanistzed** [comment] 2022-02-17 04:33
Sorry about this.
I am unable to use v4.4.0 of Dice so Nice because it's incompatible with my hardware/drivers, so I haven't been able to work on this.
I intend to revisit this when/if a new version of DSN is released that I can use and test.
I'm adding a wontfix label for now.

**Comment by arcanistzed** [comment] 2022-02-21 17:28
Ok. I've got DSN working again and I'd like to fix this. Can anyone help me reproduce the issue by sharing your configuration on Discord? Thank you.

**Comment by arcanistzed** [comment] 2022-02-21 20:50
Ok. I'm currently fairly certain this is a Dice So Nice issue as it's enforcing a limit of 53 registered fonts. Using modules such as Theatre Inserts (which includes hundreds of fonts) will bring you over that limit and cause harmless errors.

**Closed as completed by arcanistzed** 2022-02-21 20:50 UTC
Labels: bug
